apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
spec:
  ports:
  - name: tcp-3000
    port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer
