apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-nfs-storage-alertmanager
  namespace: monitoring
provisioner: fuseim.pri/ifs-alertmanager # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-nfs-storage-prometheus
  namespace: monitoring
provisioner: fuseim.pri/ifs-prometheus # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"